### ISSUE TITLE
My issue?

### ISSUE THREAD

**Issue by kaitoukid-1412** [mitchellkrogza/fail2ban-useful-scripts#1]
Thanks
![capture](https://user-images.githubusercontent.com/15698245/41473998-0a55fce0-70e5-11e8-80a9-f2f767e7afc7.PNG)

**Comment by mitchellkrogza** [comment]
@phatvip123 which script are you having a problem with?

**Comment by kaitoukid-1412** [comment]
**f2b-badips-to-hostsdeny.sh**
Ubuntu 18.04 x64, thanks!
Why do you answer me slow? I am angry with you, ahhhhhhhhhhhhhhhhhhhhhh

**Comment by mitchellkrogza** [comment]
Was away for 7 days 😄 can you explain what is inside the `abc.sh` file ?

**Comment by kaitoukid-1412** [comment]
**abc**.sh like **f2b-badips-to-hostsdeny.sh**!, i rename to easy use ^^

**Comment by mitchellkrogza** [comment]
Thanks @phatvip123  Please try changing line 40 from `_tmp=tmp` to `_tmp=/usr/tmp.txt` and please let me know if that fixes it.

**Comment by kaitoukid-1412** [comment]
worked, **Thanks**!

**Comment by mitchellkrogza** [comment]
Awesome @phatvip123 I will push a fix now for other users. Thanks for reporting this.
